version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html/latina
hooks:
  BeforeInstall:
    - location: scripts/configure_hosts_before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_hosts_after.sh
      timeout: 300
      runas: root
